"""empty message

Revision ID: 65705d7c3e45
Revises: 51a815b8a85a
Create Date: 2024-10-22 00:28:42.369491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65705d7c3e45'
down_revision = '51a815b8a85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('major')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
