"""listing picture

Revision ID: e90d474ca88f
Revises: fdaf1b05ba47
Create Date: 2024-10-22 14:41:29.064096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90d474ca88f'
down_revision = 'fdaf1b05ba47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_picture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('listing_picture')

    # ### end Alembic commands ###
